# Generated by Django 6.0.6 on 2026-06-30 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('billed_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted - awaiting compliance docs'), ('PMO_REVIEW', 'Pending PMO Clearance'), ('STATUS_CLEARED_FOR_PAYMENT', 'Cleared for Payment'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='compliance/')),
                ('document_label', models.CharField(help_text='e.g. GST proof, PF challan, ESI challan', max_length=100)),
                ('worker_count_declared', models.PositiveIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_docs', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_qty_ordered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_of_measure', models.CharField(default='unit', max_length=20)),
                ('technical_annexure', models.FileField(blank=True, null=True, upload_to='po_annexures/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft - awaiting vendor acceptance'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementBookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('mb_image', models.ImageField(upload_to='measurement_books/')),
                ('transcribed_text', models.TextField(blank=True, help_text='Reserved for future HTR/OCR pipeline output')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mb_logs', to='core.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_entry', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('loi_reference', models.CharField(help_text='Letter of Intent reference number', max_length=100)),
                ('loi_document', models.FileField(blank=True, null=True, upload_to='loi/')),
                ('is_approved', models.BooleanField(default=False, help_text='Flips True when vendor accepts PO (Step 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_onboarded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / Procurement'), ('PMO', 'PMO (Head Office)'), ('SITE_ENGINEER', 'Site Engineer'), ('QUALITY', 'Quality'), ('VERTICAL_LEAD', 'Vertical Lead'), ('VENDOR', 'Vendor')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Set only when role=VENDOR', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.vendor'),
        ),
        migrations.CreateModel(
            name='WorkCompletionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('passed_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('is_signed_by_engineer', models.BooleanField(default=False)),
                ('engineer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_signed_by_quality', models.BooleanField(default=False)),
                ('quality_signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_signed_by_vertical_lead', models.BooleanField(default=False)),
                ('vertical_lead_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcc_engineer_signs', to=settings.AUTH_USER_MODEL)),
                ('measurement_book_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='core.measurementbooklog')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.purchaseorder')),
                ('quality_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcc_quality_signs', to=settings.AUTH_USER_MODEL)),
                ('vertical_lead_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wcc_vlead_signs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.workcompletioncertificate'),
        ),
    ]
